from Bio import SeqIO

from Bio.Seq import Seq
from Bio.Alphabet import generic_dna

sequence = SeqIO.read("AgeIM.gb", "genbank")
sequence.seq = Seq("atgaaaactattgacttattctgcggtgctggtgggttaggcgaaggatttcgtcaggctggtttttctgcgctttacgcaaatgaccacgaaaccccagccttagcgacgtataaggaaaatcatccagatgctgtctgttccacagatagtattgaaacggtagatccaaagaaaatccgtgaggacttgggcgttgccccggggcaagttgatgtagtaatgggcgggccaccttgccagggattctcgacctatggccagcgtcgtgatgacgacgctcgtaatcaactttacgttccttactttgggtttgtggaagaatttcgtccaaaggcctttttgatcgagaacgttgtaggtctgttgtccatgagtggtggggcggtcctggctgacatggtagcacgtgctgaagctctggggtatgctgccgatgttgtaaccttggacgcatgcgaatacggcgtaccgcagcaccgtcgccgcgtgttcatctttggtgcggcggatgggcagcgcatcgacccgccccagccgtcgcacgtaaacggaaagcgcagtggcgtagtcttgaatgaccagccatctttgtttttcgatgggccaagcatccaaccagctttaacggtgcgcgacgccattagcgaccttcccgatgaagtcNNNNNNcctcgtgatactcagaaacccatggagtaccccgaaccgccaaagacagaataccagcgtcttatgcgtggtaacagcaccgagcttacccaccattcagccaagcgtatgcttggcattcgccgtttgcgcttagcaatgcttcaccccggcgactatggaacgaaaatcgaagaacgccttgcggatggtggcttaaacgacgaactgattgatcttatgatgggcggggcagggatgcgcgacgctgcggaatgtcgcactcaggaccgtgaaaaggaggcggccctgcgcgaggtgttgaaaggagggcataccacaccggccaaagtgatggagttcctggactcgcagggttttgccaacaagtaccgccgcttacgctgggatgctccctctcacacagtcgtcgctcacatggcgcgtgattgttcagacttcgtgcacccaggcatcgaccgtttcgtgtccgtgcgtgaagctgcacgctttcagtcgtttccagacacgtaccgcttccctggctcacagttccgccagtttcgccaaatcggcaacgcggtgcccccattgttgggccgcgccatggctgaaacgattaaagttgccattagttaa", generic_dna)
print (sequence)

SeqIO.write(sequence, "AgeI-Optimized.gb", "genbank")

