---
### Globals' configuration 

Syntheis_configuration:
    max_length: 1500
    min_length: 300

PCR_configuration:
    max_length: 5000

Standard_flanks:
    prefix: GGAG
    suffix: CGCT

Enzyme_configuration:
    - AarI:
        prefix: N
        suffix: N
    - BbsI:
         prefix: N
         suffix: N
    - BfuAI:
        prefix: N
        suffix: N
    - BsaI:
        prefix: N
        suffix: N
    - BsmBI:
        prefix: N
        suffix: N
    - BtgZI:
        prefix: N
        suffix: N
    - SapI:
        prefix: N
        suffix: N

### Part configuration
Eukaryotic_Promoter:
    # FreeGenes MoClo Eukaryotic Promoter definition
    cloning_enzyme: BbsI
    small_cloning_enzyme: BtgZI
    retrieval_enzyme: BsaI
    prefix: GGAG
    suffix: AATG

Prokaryotic_Promoter:
    # FreeGenes MoClo Prokaryotic Promoter definition
    cloning_enzyme: BbsI
    small_cloning_enzyme: BtgZI
    retrieval_enzyme: BsaI
    prefix: GGAG
    suffix: TACT

RBS:
    # FreeGenes MoClo RBS definition
    cloning_enzyme: BbsI
    small_cloning_enzyme: BtgZI
    retrieval_enzyme: BsaI
    prefix: TACT
    suffix: AATG

Terminator:
    # FreeGenes MoClo Prokaryotic Promoter definition
    cloning_enzyme: BbsI
    small_cloning_enzyme: BtgZI
    retrieval_enzyme: BsaI
    prefix: GCTT
    suffix: CGCT


...
